version: '3.0'

services:
  webapplicationsample.mssql:
    image: mcr.microsoft.com/azure-sql-edge
    restart: unless-stopped
    environment:
      - MSSQL_SA_PASSWORD=Password123
      - ACCEPT_EULA=1
    ports:
      - '1433:1433'