name: Publish NuGet

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack "src/DeezNuts.Hangfire.ApplicationInsights/DeezNuts.Hangfire.ApplicationInsights.csproj" --no-build --output nupkgs --configuration Release

      - name: Publish
        run: dotnet nuget push **/*.nupkg --api-key "${{secrets.NUGET_API_KEY}}" --source https://api.nuget.org/v3/index.json
